name: alice_lightweight
description: Lightweight Alice version. Removed additional dependencies except dio. Version is in sync with orginal alice
version: 0.3.3
homepage: https://github.com/jhomlala/alice

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  dio: ^5.1.2
  rxdart: ^0.27.7
  share_plus: ^7.0.2
  path_provider: ^2.0.10
